---
# This Ansible playbook is used to deploy a PyWPS application.
- name: Install a PyWPS application
  hosts: all
  become: yes

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Include vars from custom.yml if found
      include_vars: "{{ item }}"
      with_first_found:
       - custom.yml
       - null.yml
  roles:
    - role: geerlingguy.repo-epel
      when: ansible_os_family == "RedHat"
    - common
    - role: andrewrothstein.miniconda
      tags:
        conda
    - role: geerlingguy.supervisor
      tags:
        supervisor
    - role: jdauphant.ssl-certs
      tags:
        nginx
    - role: geerlingguy.nginx
      tags:
        nginx
    - role: ANXS.postgresql
      when: db_install_postgresql
      tags:
        db
    - pywps
  tasks:
    - name: Upgrade pip
      command: pip install --upgrade pip

    - name: Install WPS services
      shell: make install
      args:
        chdir: "{{ src_dir }}/{{ item.repo|basename }}"
      environment:
        PATH: /usr/local/anaconda/envs/{{ item.repo|basename }}/bin:{{ ansible_env.PATH }}
      with_items: "{{ wps_services }}"
