---
# This Ansible playbook is used to deploy a PyWPS application.
- name: Install a PyWPS application
  hosts: all
  vars:
    pyramid_prefix: "{{ ansible_env.HOME }}"
  roles:
    - role: andrewrothstein.miniconda
      miniconda_parent_dir: "{{ ansible_env.HOME }}"
  tasks:
    - name: Clone pyramid-phoenix
      git:
        repo: 'https://github.com/bird-house/pyramid-phoenix'
        version: master
        dest: "{{ ansible_env.HOME }}/pyramid-phoenix"

    - name: Create conda environemnt
      shell: "{{ ansible_env.HOME  }}/anaconda/bin/conda env create -f environment.yml"
      args:
        chdir: "{{ ansible_env.HOME }}/pyramid-phoenix"
      ignore_errors: True
