---

# miniconda from Ansible Galaxy
- src: andrewrothstein.miniconda

# Installs the EPEL repository (Extra Packages for Enterprise Linux) for RHEL/CentOS.
# https://github.com/geerlingguy/ansible-role-repo-epel
- src: geerlingguy.repo-epel

# supervisor form Ansible Galaxy
- src: geerlingguy.supervisor
  version: 2.0.2
#- src: https://github.com/geerlingguy/ansible-role-supervisor.git
#  version: origin/master

# nginx form Ansible Galaxy
- src: geerlingguy.nginx

# postgres from Ansible Galaxy
- src: geerlingguy.postgresql
