---
- include: prepare.yml

- include: sqlite.yml
  when: db_install_sqlite

- include: config.yml

- include: fileserver.yml
  when: fs_enabled

- name: Assure application running at end of playbook
  command: /bin/true
  notify:
    - restart pywps
    - restart nginx
  tags:
    - pywps
    - nginx
    - conf
