---
- name: Clone WPS.
  git:
    repo: "{{ item.repo | default('https://github.com/bird-house/'+item.name+'.git') }}"
    version: "{{ item.version | default('master') }}"
    dest: "{{ src_dir }}/{{ item.name }}"
    update: yes
    force: yes
  with_items: "{{ wps_services }}"
  register: git
  tags:
    - pywps
    - git

- name: Create Conda environment from environment file.
  command: "{{ conda_location }}/bin/conda env update -p {{ conda_envs_dir}}/{{ item.name }}"
  args:
    chdir: "{{ src_dir }}/{{ item.name }}"
  with_items: "{{ wps_services }}"
  when: git.changed
  register: conda
  tags:
    - pywps
    - conda

- name: Install additional Conda packages.
  command: "{{ conda_location }}/bin/conda install -p {{ conda_envs_dir}}/{{ item.name }} gunicorn psycopg2"
  with_items: "{{ wps_services }}"
  when: conda.changed
  tags:
    - pywps
    - conda

- name: Create folders used by PyWPS and set owner
  file: path={{ item }} state=directory owner={{ wps_user }} group={{ wps_group }} mode=0755
  with_items:
    - /etc/gunicorn
    - /etc/pywps
    - /var/log/pywps
    - /var/run/pywps
    - /var/lib/pywps/db
  tags:
    - pywps
    - conf

- name: Create output folders used by PyWPS and set owner
  file: path="/var/lib/pywps/outputs/{{ item.name }}" state=directory owner={{ wps_user }} group={{ wps_group }} mode=0755
  with_items:
    - "{{ wps_services }}"
  tags:
    - pywps
    - conf

- name: Create temp folders used by PyWPS and set owner
  file: path="/var/lib/pywps/tmp/{{ item.name }}" state=directory owner={{ wps_user }} group={{ wps_group }} mode=0755
  with_items:
    - "{{ wps_services }}"
  tags:
    - pywps
    - conf

- name: Update log file permissions
  file: path="/var/log/pywps/{{ item.name }}.log" state=touch owner={{ wps_user }} group={{ wps_group }} mode=0644
  with_items:
    - "{{ wps_services }}"
  tags:
    - pywps
    - conf
