- include_tasks: Debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Install common packages
  package: name={{ item }} state=latest
  with_items:
    - python-pip
    - wget
    - curl
    - git
  tags:
    - common

- name: Add WPS group
  group:
    name: "{{ wps_group }}"
    gid: "{{ wps_gid | default(omit) }}"
    state: present

- name: Add WPS user
  user:
    name: "{{ wps_user }}"
    uid: "{{ wps_uid | default(omit) }}"
    groups: "{{ wps_group }}"
    system: yes
    shell: /sbin/nologin
    createhome: no
    home: "{{ wps_user_home }}"
  when: wps_add_user
