---
- name: restart pywps
  supervisorctl:
    name: "{{ wps_name }}"
    state: restarted
    username: "{{ supervisor_user }}"
    password: "{{ supervisor_password }}"

- name: restart nginx
  service:
    name: nginx
    state: restarted
